name: Docker Hub CD Process

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  build-and-publish:
    name: Build and publish image in Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: FIAP Produto Service
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build package with Maven
        run: mvn -B clean package -DskipTests

      - name: Moving artifact to staging folder
        run: mkdir staging && cp target/fiap-produto-service-0.0.1-SNAPSHOT.jar staging

      - name: Uploading artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: staging

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/fiap-produto-service:latest